import {
  AlarmClock,
  ArrowDown,
  ArrowUp,
  Award,
  BookMarked,
  BookOpen,
  Briefcase,
  Building2,
  CalendarClock,
  Check,
  CheckCheck,
  Circle,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleSlash,
  CircleX,
  ClipboardList,
  Clock,
  Coffee,
  Copy,
  FileText,
  Flame,
  FlaskConical,
  GraduationCap,
  HeartPulse,
  History,
  Milestone,
  Minus,
  NotebookPen,
  Plus,
  RefreshCw,
  Rocket,
  Siren,
  Tag,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  User,
  Users,
  type LucideIcon
} from 'lucide-react'

/**
 * Icons referenced by name from `src/shared/constants/{categories,statuses}.ts`. A curated map keeps
 * the bundle tree-shakeable (importing all of lucide would add ~1 MB).
 */
export const ICONS_BY_NAME: Readonly<Record<string, LucideIcon>> = {
  AlarmClock,
  ArrowDown,
  ArrowUp,
  Award,
  BookMarked,
  BookOpen,
  Briefcase,
  Building2,
  CalendarClock,
  Check,
  CheckCheck,
  Circle,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleSlash,
  CircleX,
  ClipboardList,
  Clock,
  Coffee,
  Copy,
  FileText,
  Flame,
  FlaskConical,
  GraduationCap,
  HeartPulse,
  History,
  Milestone,
  Minus,
  NotebookPen,
  Plus,
  RefreshCw,
  Rocket,
  Siren,
  Tag,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  User,
  Users
}

/** Resolves a lucide icon by its constant name; unknown names fall back to a plain circle. */
export const iconByName = (name: string): LucideIcon => ICONS_BY_NAME[name] ?? Circle
